---
af: za
en: us
da: dk
sv: se
sq: al
nb: 'no'
ja: jp
kk: kz
ko: kr
ky: kg
hy: am
ms: bn
be: by
bg: bh
ca: ad
zh: cn
sr: rs
sl: si
et: ee
sw: tz
ta: lk
ka: gs
el: gr
uk: ua
he: il
hi: in
vi: vn
dizzle: us
